version: '2'

services:
    webcrawler:
        image: 'webcrawler:latest'
        build:
            dockerfile: docker/webcrawler/Dockerfile
            context: .
        container_name: webcrawler
        restart: always
        depends_on:
            - cassandra
            - cache
        ports:
            - "8080:8080"
        networks:
            - webnet
    cache:
        image: 'redis'
        hostname: cache
        container_name: webcrawler_cache
        ports:
            - "6379:6379"
        networks:
            - webnet
    cassandra:
        build:
            dockerfile: docker/cassandra/Dockerfile
            context: .
        container_name: webcrawler_cassandra
        expose:
            - 9042
        ports:
            - "9042:9042"
        environment:
            CASSANDRA_DC: datacenter1
            CASSANDRA_LISTEN_ADDRESS: cassandra
        networks:
            - webnet
networks:
    webnet: