version: '2'

services:
    webcrawler:
        image: 'webcrawler:latest'
        build:
            dockerfile: Dockerfile
            context: .
        container_name: webcrawler
        depends_on:
            - cache
        ports:
            - "8080:8080"
        networks:
            - webnet
    cache:
        image: 'redis'
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        networks:
            - webnet
networks:
    webnet: