package com.webcrawler.configkeyenum;

import lombok.Getter;

// The getKey(), getCacheKey() and getDefaultValue() method generated by lombok's @Getter annotation will override the IConfigKey interface
@Getter
public enum ConfigKey implements IConfigKey {

    MAX_REQUEST_TO_WEBSITE("webcrawler-max-request", "webcrawler_max_request" ,"50");
    private final String key;

    private final String cacheKey;
    private final String defaultValue;

    ConfigKey(String key, String cacheKey, String defaultValue){
        this.cacheKey = cacheKey;
        this.key = key;
        this.defaultValue = defaultValue;
    }
}
